#!/usr/bin/python

'''dotfiles keeps your ~/.* synchronized across machines.
Usage:

dotfiles init REPO

  Initializes dotfiles using REPO. REPO is where the master copy of
  your dotfiles will be stored.

dotfiles install REPO

  Installs dotfiles from REPO into your ~ on this
  machine. Creates ~/.dotfiles/ if it does not exist; complains and
  exits with error if a ~/.dotfiles does exist.

  Pulls files from REPO into ~/.dotfiles/...

  FIXME: Needs to deal with existing files in a sane way.

dotfiles add DOTFILE

  If DOTFILE is not under ~, complain and exit with error.

  If DOTFILE is already a controlled file, do the equivalent of a "git
  add".

  *Move* DOTFILE into ~/.dotfiles and create a symlink from the
  original file to the ~/.dotfiles version. If DOTFILE is in a
  subdir, the subdirs will be created under ~/.dotfiles. Adds
  DOTFILE to the REPO (locally: it does not do the push/checkin).

  If DOTFILE is a directory, everything under the directory will be
  placed under dotfiles control. The directory itself will become a
  symlink into the REPO. If you do not want to control the entire
  directory, pick and choose the files you want to control. Mixing and
  matching is probably a bad idea.

dotfiles diff

  Show diffs of changed controlled files.

dotfiles push COMMIT-MSG

  Sends local changes to REPO. Similar semantics to git push, svn ci
  -- e.g. behavior if local is out of date w.r.t REPO.

dotfiles pull

  Fetches updates from REPO. Similar semantics to git pull, svn up
  -- e.g. behavior when merge required.

  When new files appear, it creates links from ~/... to
  ~/.dotfiles/...

  FIXME: Deal with existing files of the same name in a sane
  way. (See above, same problem.)

dotfiles status

  Lists controlled files that are changed, and/or those that have been
  staged for the next push.
'''

__version__ = "0.4"
__date__ = "2012-05-23"
__author__ = "Brian St. Pierre (http://bstpierre.org/)"
__copyright__ = "Copyright 2009, 2012, Brian St. Pierre"
__license__ = "MIT"


import optparse
import os
import shutil
import subprocess
import sys
import tempfile

# This is where we store our control info.
_DOTFILES_DIR = os.path.join(os.environ.get('HOME', ''),
                             '.dotfiles')

# This is where copies of the dotfiles live (e.g. .emacs).
_LOCAL_REPO_DIR = os.path.join(_DOTFILES_DIR, 'repo')


def _maybe_warn(link):
    '''Print a warning about the fact that link exists.

    Unless it is in a parent directory that is linked into the
    repo.'''

    home = os.environ.get('HOME', None)
    if not home:
        return

    dir = os.path.dirname(link)
    while dir not in ['/', home]:
        if os.path.islink(dir):
            target = os.readlink(dir)
            if _LOCAL_REPO_DIR in target:
                # A parent dir is pointing into the repo, don't warn.
                return
        dir = os.path.dirname(dir)
    print 'WARNING: %s exists, skipping' % link


def _make_links_to_repo(warn_on_existing_links=False):
    the_readme = os.path.join(_LOCAL_REPO_DIR, 'README')
    dirs = ['']
    while len(dirs):
        dir = dirs.pop()
        for f in os.listdir(os.path.join(_LOCAL_REPO_DIR, dir)):
            if f == '.git':
                continue
            path = os.path.join(_LOCAL_REPO_DIR, dir, f)
            if path == the_readme:
                # No need to force the dummy README file to show up in
                # the user's $HOME/.
                continue
            if os.path.isdir(path):
                dirs.append(os.path.join(dir, f))
                continue
            if os.path.isfile(path):
                linkdir = os.path.join(os.environ.get('HOME', ''),
                                       dir)
                if not os.path.isdir(linkdir):
                    os.makedirs(linkdir)
                link = os.path.join(linkdir, f)
                if os.path.exists(link):
                    # If warn_on_existing_links is set, we warn (and
                    # skip the file).
                    #
                    # If the file is not a symlink, we warn (and skip
                    # the file).
                    #
                    # Otherwise the file is a symlink and we can just
                    # ignore it -- assume dotfiles already controls
                    # it.
                    if (not os.path.islink(link) or
                        warn_on_existing_links):
                        _maybe_warn(link)
                    continue
                os.symlink(path, link)


def _fix_permissions():
    permissions_meta = os.path.join(_LOCAL_REPO_DIR,
                                    'dotfiles_permissions.config')
    if not os.path.exists(permissions_meta):
        return

    for line in open(permissions_meta, 'r').readlines():
        line = line.strip()
        record = line.split(',')
        if len(record) != 2:
            print 'WARNING: invalid permission line "%s"' % (line, )
            continue
        file, mode = record

        try:
            mode = int(mode, 8)
        except ValueError:
            print 'WARNING: bad file mode "%s"' % mode
            continue

        if file[0] == '/' or '..' in file:
            print 'WARNING: path not relative to $HOME: "%s"' % (file, )
            continue

        file_path = os.path.join(_LOCAL_REPO_DIR, file)
        if not os.path.exists(file_path):
            print 'WARNING: file not found: "%s"' % (file_path, )
            continue

        try:
            os.chmod(file_path, mode)
        except StandardError, ex:
            print 'WARNING: chmod "%s" "0%o" failed: %s' % (
                file, mode, ex)


def dotfiles_init(*args):
    if len(args) != 1:
        print __doc__
        return 1

    repo = args[0]

    if not os.path.exists(repo):
        os.makedirs(repo)

    retcode = subprocess.call('git init --bare', cwd=repo, shell=True)
    if retcode:
        print 'error creating git repo'
        return retcode

    # Clone into, and create the first commit from, a temp dir.
    clone_parent = tempfile.mkdtemp()
    retcode = subprocess.call('git clone %s' % (repo, ),
                              cwd=clone_parent, shell=True)
    if retcode:
        print 'error cloning git repo'
        return retcode

    # The clone dir really gets created as a subdirectory of the cwd.
    clone_dir = os.path.join(clone_parent, os.path.basename(repo))

    print 'Created clone in "%s"' % (clone_dir, )
    f = open(os.path.join(clone_dir, 'README'), 'w')
    f.write('''This is a dotfiles repository.

See http://github.com/bstpierre/dotfiles for more information.\n''')
    f.close()

    retcode = subprocess.call('git add README',
                              cwd=clone_dir,
                              shell=True)
    if retcode:
        print 'error adding README to clone'
        return retcode

    retcode = subprocess.call('git commit '+
                              '-m"New dotfiles repository"',
                              cwd=clone_dir,
                              shell=True)
    if retcode:
        print 'error commiting to clone'
        return retcode

    retcode = subprocess.call('git push origin master',
                              cwd=clone_dir,
                              shell=True)
    if retcode:
        print 'error pushing from clone to origin'
        return retcode

    shutil.rmtree(clone_parent)

    return retcode


def dotfiles_install(*args):
    '''Installs dotfiles from REPO into your ~ on this
    machine. Creates ~/.dotfiles/ if it does not exist; complains and
    exits with error if a ~/.dotfiles does exist.

    Pulls files from REPO into ~/.dotfiles/...
    '''

    if len(args) != 1:
        print __doc__
        return 1

    repo = args[0]

    if os.path.exists(_DOTFILES_DIR):
        print 'error: dotfiles control dir "%s" exists already' % (
            _DOTFILES_DIR)
        return 1

    os.makedirs(_DOTFILES_DIR)
    retcode = subprocess.call('git clone %s %s' % (
                                  repo, _LOCAL_REPO_DIR),
                              shell=True)

    _make_links_to_repo(warn_on_existing_links=True)

    return retcode


def dotfiles_add(*args):
    if len(args) < 1:
        print __doc__
        return 1

    home = os.environ.get('HOME', None)
    if not home:
        print 'error: $HOME is not set, exiting'
        return 1

    for file in args:
        if file.find(home) != 0:
            # Maybe the name is relative to $HOME?
            if not os.path.exists(os.path.join(home, file)):
                print 'WARNING: %s is not under $HOME (%s), skipping' % (
                    file, home)
                continue
            else:
                file = os.path.join(home, file)
                print 'INFO: using %s' % os.path.join(home, file)
        filename = file.replace(home, '').strip(os.path.sep)
        repofile = os.path.join(_LOCAL_REPO_DIR, filename)
        repodir = os.path.dirname(repofile)
        if not os.path.exists(repodir):
            os.makedirs(repodir)

        if not os.path.exists(repofile):
            # This file is being newly controlled.
            os.rename(file, repofile)
            os.symlink(repofile, file)
        else:
            # This file is already under control; nothing to do.
            pass

        retcode = subprocess.call(
            'git add ' + filename,
            cwd=_LOCAL_REPO_DIR,
            shell=True)
        if retcode != 0:
            print 'error: git add failed adding %s, ' % filename + \
                  'your dotfiles are probably in an inconsistent state'
            return retcode


def dotfiles_diff(*args):
    if len(args):
        print __doc__
        return 1

    retcode = subprocess.call(
        'git diff',
        cwd=_LOCAL_REPO_DIR,
        shell=True)
    if retcode != 0:
        print 'error: git diff failed'

    return retcode


def dotfiles_push(*args):
    if len(args) != 1:
        print __doc__
        return 1

    msg = args[0]
    retcode = subprocess.call(
        'git commit -a -m"%s"' % (msg, ),
        cwd=_LOCAL_REPO_DIR,
        shell=True)
    if retcode != 0:
        print 'error: git commit failed, your dotfiles ' + \
              'are probably in an inconsistent state'
        return retcode

    retcode = subprocess.call(
        'git push',
        cwd=_LOCAL_REPO_DIR,
        shell=True)
    if retcode != 0:
        print 'error: git push failed, your dotfiles ' + \
              'are probably in an inconsistent state'
        return retcode

    return retcode


def dotfiles_pull(*args):
    if len(args):
        print __doc__
        return 1

    retcode = subprocess.call(
        'git pull',
        cwd=_LOCAL_REPO_DIR,
        shell=True)
    if retcode != 0:
        print 'error: git pull failed, your dotfiles ' + \
              'are probably in an inconsistent state'
        return retcode

    _make_links_to_repo(warn_on_existing_links=False)
    _fix_permissions()

    return retcode


def dotfiles_status(*args):
    if len(args):
        print __doc__
        return 1

    retcode = subprocess.call(
        'git status',
        cwd=_LOCAL_REPO_DIR,
        shell=True)
    if retcode != 0:
        print 'error: git status failed'
    return retcode


def main():
    parser = optparse.OptionParser(usage=__doc__)

    options, remaining = parser.parse_args(sys.argv)

    if len(remaining) < 2:
        parser.print_usage()
        sys.exit(1)

    mode = remaining[1]
    handler = globals().get('dotfiles_' + mode, None)
    if handler:
        status = handler(*remaining[2:])
    else:
        print 'dotfiles: unknown mode "%s"' % mode
        status = 1

    sys.exit(status)


if __name__ == '__main__':
    main()
